import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "Always"

[font]
size = 13.0

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"

[window.padding]
x = 10
y = 10

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"
