live_config_reload = true

[colors.bright]
black = "0x545862"
blue = "0x565c64"
cyan = "0xbe5046"
green = "0x353b45"
magenta = "0xb6bdca"
red = "0xd19a66"
white = "0xc8ccd4"
yellow = "0x3e4451"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
blur = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10
