command_timeout = 100000
scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
