require("insidemordecai.lualine")
require("insidemordecai.telescope")
require("insidemordecai.gitsigns")
require("insidemordecai.nvim-tree")
require("insidemordecai.lsp")
require("insidemordecai.autopairs")
require("insidemordecai.colorizer")
require("insidemordecai.comment")
